openapi: 3.0.0
info:
  title: Complex Express API Demo
  version: 1.0.0
  description: |
    A more advanced demo Express API with multiple endpoints, request validation,
    and full Swagger documentation.

servers:
  - url: http://localhost:3000
